services:
  - type: web
    name: task-management-backend
    runtime: node
    plan: free
    rootDir: task-management-app
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
